import { Platform, StyleSheet } from "react-native";
import { accent, spacing, backgrounds, text, fontFamilies, fontSizes, radii } from "@orion/shared/tokens";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: backgrounds.base,
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorTitle: { color: text.primary, fontSize: fontSizes.md, fontWeight: '700', textAlign: 'center', marginHorizontal: spacing[6], marginTop: spacing[3] },
  retryButton: { minHeight: 44, marginTop: spacing[4], paddingHorizontal: spacing[5], borderRadius: radii.xl, backgroundColor: accent.primary, flexDirection: 'row', gap: 8, alignItems: 'center' },
  retryButtonText: { color: '#fff', fontWeight: '800' },
  primaryWatchAction: { width: '100%' },
  secondaryActions: { flexDirection: 'row', gap: spacing[2], flexWrap: 'wrap', flex: 1 },
  actionRowTablet: { maxWidth: 720 },
  moreOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.65)' },
  moreSheet: { backgroundColor: backgrounds.elevated, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: spacing[5], paddingBottom: Platform.OS === 'ios' ? 38 : 24, borderTopWidth: 1, borderColor: 'rgba(255,255,255,0.12)' },
  moreHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing[3] },
  moreTitle: { color: text.primary, fontSize: fontSizes.lg, fontWeight: '900' },
  moreClose: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.08)' },
  moreAction: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: spacing[3], paddingVertical: spacing[2], borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)' },
  moreActionText: { color: text.primary, fontSize: fontSizes.sm, fontWeight: '700' },
  moreActionDescription: { color: text.muted, fontSize: fontSizes.xs, lineHeight: 17 },
  moreNotice: { flexDirection: 'row', gap: spacing[3], paddingTop: spacing[4] },
  backButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 25,
    left: 20,
    zIndex: 100,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(5, 5, 10, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  backdropContainer: {
    height: 280,
    width: '100%',
    position: 'relative',
  },
  backdropImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  backdropGradient: {
    ...StyleSheet.absoluteFill,
  },
  detailsContent: {
    marginTop: -80,
    paddingHorizontal: spacing[4],
  },
  headerRow: {
    flexDirection: 'row',
    gap: spacing[4],
    alignItems: 'flex-end',
  },
  posterImage: {
    width: 105,
    height: 155,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  headerMeta: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingBottom: spacing[1],
  },
  titleText: {
    color: '#ffffff',
    fontSize: 22,
    fontFamily: fontFamilies.display,
    fontWeight: '900',
    letterSpacing: -0.5,
    marginBottom: spacing[2],
    textShadowColor: 'rgba(0, 0, 0, 0.95)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  metaBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    flexWrap: 'wrap',
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(251, 191, 36, 0.15)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.3)',
  },
  metaText: {
    color: 'rgba(255, 255, 255, 0.75)',
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.body,
    fontWeight: '600',
  },
  hdBadge: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  hdText: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 9,
    fontFamily: fontFamilies.heading,
    fontWeight: '900',
  },
  genreInlineRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: spacing[1],
  },
  genreInlineText: {
    color: '#f87171',
    fontSize: 10,
    fontFamily: fontFamilies.heading,
    fontWeight: '800',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    marginTop: spacing[3],
  },
  pressed: {
    transform: [{ scale: 0.97 }],
  },
  playWrapper: {
    flex: 1,
    position: 'relative',
  },
  playButtonGlow: {
    ...StyleSheet.absoluteFill,
    backgroundColor: accent.primary,
    borderRadius: radii.lg,
    opacity: 0.6,
  },
  playButton: {
    flexDirection: 'row',
    backgroundColor: accent.primary,
    paddingVertical: spacing[3],
    borderRadius: radii.lg,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  playButtonText: {
    color: '#fff',
    fontSize: fontSizes.md,
    fontFamily: fontFamilies.heading,
    fontWeight: '800',
  },
  downloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    paddingHorizontal: 14,
    height: 48,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: '#10b981',
  },
  downloadButtonText: {
    color: '#10b981',
    fontSize: 13,
    fontFamily: fontFamilies.heading,
    fontWeight: '800',
  },
  listButton: {
    width: 48,
    height: 48,
    borderRadius: radii.xl,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  trailerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 16,
    height: 48,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  trailerBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  unreleasedBannerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
    marginBottom: spacing[4],
  },
  unreleasedBannerText: {
    color: '#f87171',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  posterWrapper: {
    position: 'relative',
    borderRadius: radii.xl,
    overflow: 'hidden',
  },
  posterLockOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(13, 13, 22, 0.82)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  posterLockText: {
    color: '#f87171',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  unreleasedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    paddingHorizontal: 20,
    height: 48,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
  },
  unreleasedBtnText: {
    color: '#f87171',
    fontSize: 14,
    fontWeight: '900',
  },
  tabsContainer: {
    marginTop: spacing[5],
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  tabPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: radii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  tabPillActive: {
    backgroundColor: 'rgba(229, 9, 20, 0.2)',
    borderColor: accent.primary,
  },
  tabPillText: {
    color: 'rgba(255, 255, 255, 0.65)',
    fontSize: 13,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  tabPillTextActive: {
    color: '#ffffff',
    fontWeight: '800',
  },
  tabContent: {
    marginTop: spacing[4],
  },
  overviewText: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 14,
    fontFamily: fontFamilies.body,
    lineHeight: 22,
    fontWeight: '400',
  },
  subSectionTitle: {
    color: text.muted,
    fontSize: 10,
    fontFamily: fontFamilies.heading,
    fontWeight: '800',
    letterSpacing: 1.5,
    marginBottom: spacing[3],
  },
  castSection: {
    marginTop: spacing[2],
  },
  castScroll: {
    marginHorizontal: -spacing[4],
    paddingHorizontal: spacing[4],
  },
  castCard: {
    width: 106,
    minHeight: 142,
    marginRight: spacing[3],
    alignItems: 'center',
    padding: spacing[2],
    borderRadius: radii.lg,
    borderWidth: 1,
  },
  castImage: {
    width: 78,
    height: 78,
    borderRadius: 39,
    marginBottom: spacing[2],
    borderWidth: 1,
  },
  castName: {
    fontSize: fontSizes.xs,
    fontFamily: fontFamilies.body,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 2,
  },
  castCharacter: {
    fontSize: 10,
    fontFamily: fontFamilies.body,
    textAlign: 'center',
  },
  placeholderText: {
    color: text.muted,
    fontFamily: fontFamilies.body,
    fontSize: fontSizes.sm,
    paddingVertical: spacing[4],
  },
  seasonPill: {
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    marginRight: spacing[2],
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  seasonPillActive: {
    backgroundColor: accent.primary,
    borderColor: accent.primary,
  },
  seasonPillText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  seasonPillTextActive: {
    color: '#fff',
  },
  episodesListContainer: {
    marginTop: spacing[1],
    gap: 12,
  },
  episodeCard: {
    flexDirection: 'row',
    gap: 12,
    padding: 10,
    borderRadius: radii.xl,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  epThumbWrapper: {
    position: 'relative',
    width: 125,
    height: 75,
    borderRadius: radii.md,
    overflow: 'hidden',
  },
  episodeListThumb: {
    width: '100%',
    height: '100%',
  },
  emptyThumb: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playBadgeOverlay: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(229, 9, 20, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  episodeListInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  epMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  episodeListNum: {
    color: accent.primary,
    fontSize: 11,
    fontFamily: fontFamilies.heading,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  epStarBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: 'rgba(251, 191, 36, 0.12)',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
  },
  epStarText: {
    color: '#fbbf24',
    fontSize: 9,
    fontWeight: '800',
  },
  epRuntimeText: {
    color: text.muted,
    fontSize: 10,
    fontWeight: '600',
  },
  episodeListDate: {
    color: text.muted,
    fontSize: 10,
  },
  episodeListName: {
    color: '#fff',
    fontSize: 14,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
    marginBottom: 3,
  },
  episodeOverviewText: {
    color: 'rgba(255, 255, 255, 0.65)',
    fontSize: 11,
    lineHeight: 15,
    marginBottom: 6,
  },
  epActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  epDownloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(229, 9, 20, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: 'rgba(229, 9, 20, 0.25)',
  },
  epDownloadBtnText: {
    color: accent.primary,
    fontSize: 10,
    fontFamily: fontFamilies.heading,
    fontWeight: '800',
  },
});
