const { session } = require("electron");
const fs = require("fs");

async function exportSessionCookies(targetUrl, tempFilePath) {
  try {
    const cookies = await session.fromPartition("persist:player").cookies.get({ url: targetUrl });
    if (!cookies?.length) return false;
    const lines = ["# Netscape HTTP Cookie File", "# This file is generated by Orion. Do not edit.", ""];
    for (const cookie of cookies) {
      lines.push([
        cookie.domain,
        cookie.hostOnly ? "FALSE" : "TRUE",
        cookie.path,
        cookie.secure ? "TRUE" : "FALSE",
        cookie.expirationDate ? Math.round(cookie.expirationDate) : 0,
        cookie.name,
        cookie.value,
      ].join("\t"));
    }
    fs.writeFileSync(tempFilePath, lines.join("\n"), "utf8");
    return true;
  } catch (error) {
    console.error("Failed to export cookies:", error);
    return false;
  }
}

module.exports = { exportSessionCookies };
