import { Platform, StyleSheet } from "react-native";
import { text, backgrounds, radii, spacing, fontSizes, fontFamilies, accent } from "@orion/shared/tokens";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: backgrounds.base,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: spacing[4],
    marginBottom: spacing[4],
    backgroundColor: backgrounds.surface,
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    height: 46,
    paddingHorizontal: spacing[4],
  },
  searchIcon: {
    marginRight: spacing[2],
  },
  clearIcon: {
    marginLeft: spacing[2],
  },
  searchInput: {
    flex: 1,
    color: text.primary,
    fontSize: fontSizes.md,
    height: '100%',
    fontFamily: fontFamilies.body,
    ...(Platform.OS === 'web' ? ({ outlineStyle: 'none' } as any) : {}),
  },
  filterContainer: {
    marginBottom: spacing[4],
  },
  filterScroll: {
    paddingHorizontal: spacing[4],
    gap: spacing[2],
  },
  filterPill: {
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  filterPillActive: {
    backgroundColor: accent.primary,
    borderColor: accent.primary,
  },
  filterPillText: {
    color: text.primary,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.body,
    fontWeight: '600',
  },
  filterPillTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  gridContainer: {
    paddingHorizontal: spacing[4],
    paddingTop: spacing[2],
  },
  row: {
    justifyContent: 'flex-start',
    gap: spacing[3],
    marginBottom: spacing[6],
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
  },
  emptyText: {
    color: text.secondary,
    fontSize: fontSizes.md,
    fontFamily: fontFamilies.body,
  },
  typeToggle: {
    flexDirection: 'row',
    paddingHorizontal: spacing[4],
    gap: spacing[2],
    marginBottom: spacing[4],
  },
  typePill: {
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  typePillActive: {
    backgroundColor: accent.primary,
    borderColor: accent.primary,
  },
  typePillText: {
    color: text.secondary,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '600',
  },
  typePillTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  regionSelectorContainer: {
    marginBottom: spacing[3],
  },
  regionPill: {
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  regionPillActive: {
    backgroundColor: accent.primary,
    borderColor: accent.primary,
  },
  regionPillText: {
    color: text.secondary,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '600',
  },
  regionPillTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  subfilterContainer: {
    marginBottom: spacing[5],
  },
  subfilterScroll: {
    paddingHorizontal: spacing[4],
    gap: spacing[2],
  },
  subfilterPill: {
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1.5],
    borderRadius: radii.full,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  subfilterPillActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  subfilterPillText: {
    color: text.muted,
    fontSize: fontSizes.xs,
    fontFamily: fontFamilies.body,
    fontWeight: '600',
  },
  subfilterPillTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  regionShelf: {
    marginBottom: spacing[5],
  },
  regionShelfTitle: {
    color: text.primary,
    fontSize: fontSizes.lg,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  emptyRegionText: {
    color: text.muted,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.body,
    fontStyle: 'italic',
    paddingHorizontal: spacing[4],
  },
  browseTitle: {
    color: text.primary,
    fontSize: fontSizes.lg,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
    paddingHorizontal: spacing[4],
    marginBottom: spacing[4],
  },
  genreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: spacing[4],
    gap: spacing[3],
  },
  genreCard: {
    height: 76,
    borderRadius: radii.xl,
    justifyContent: 'center',
    paddingHorizontal: spacing[3],
    backgroundColor: '#0f0f18',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  genreCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  genreIconBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  genreCardText: {
    flex: 1,
    color: '#ffffff',
    fontSize: 13,
    fontFamily: fontFamilies.heading,
    fontWeight: '800',
    letterSpacing: 0.2,
    textShadowColor: 'rgba(0,0,0,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  genreHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing[4],
    marginBottom: spacing[3],
    gap: spacing[3],
  },
  backPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  backPillText: {
    color: '#fff',
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '600',
  },
  genreActiveLabel: {
    color: accent.primary,
    fontSize: fontSizes.xl,
    fontFamily: fontFamilies.display,
    fontWeight: '900',
    letterSpacing: -0.3,
    flex: 1,
  },
  filterControlsBar: {
    marginBottom: spacing[4],
  },
  dropdownPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    gap: 6,
  },
  dropdownPillActive: {
    backgroundColor: accent.primary,
    borderColor: accent.primary,
  },
  dropdownPillText: {
    color: text.secondary,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '600',
  },
  dropdownPillTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  regionShelfHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing[4],
    marginBottom: spacing[3],
  },
  browseAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(229, 9, 20, 0.15)',
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1.5],
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: 'rgba(229, 9, 20, 0.3)',
  },
  browseAllBtnText: {
    color: accent.primary,
    fontSize: fontSizes.xs,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  loadMoreFooter: {
    alignItems: 'center',
    marginVertical: spacing[4],
  },
  loadMoreButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: spacing[6],
    paddingVertical: spacing[3],
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  loadMoreButtonText: {
    color: '#fff',
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#14141f',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: spacing[5],
    paddingBottom: Platform.OS === 'ios' ? 40 : spacing[6],
    paddingTop: spacing[3],
    borderTopWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    alignSelf: 'center',
    marginBottom: spacing[3],
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  modalTitle: {
    color: '#fff',
    fontSize: fontSizes.lg,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  modalCloseBtn: {
    padding: 4,
  },
  modalOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing[3.5],
    paddingHorizontal: spacing[3],
    borderRadius: radii.md,
    marginBottom: spacing[1],
  },
  modalOptionActive: {
    backgroundColor: 'rgba(229, 9, 20, 0.12)',
  },
  modalOptionText: {
    color: text.secondary,
    fontSize: fontSizes.md,
    fontFamily: fontFamilies.body,
    fontWeight: '500',
  },
  modalOptionTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
});
