import { Platform, StyleSheet } from "react-native";
import { radii, spacing, fontSizes, fontFamilies } from "@orion/shared/tokens";
import type { MobileThemeTokens } from "../../context/ThemeContext";

export const createDiscoverStyles = (theme: MobileThemeTokens) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: spacing[4],
    marginBottom: spacing[4],
    backgroundColor: theme.input,
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: theme.border,
    height: 46,
    paddingHorizontal: spacing[4],
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
  },
  searchContainerFocused: {
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  searchIcon: {
    marginRight: spacing[2],
  },
  clearButton: {
    width: 40,
    height: 40,
    marginRight: -8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  searchInput: {
    flex: 1,
    color: theme.text,
    fontSize: fontSizes.md,
    height: '100%',
    fontFamily: fontFamilies.body,
    ...(Platform.OS === 'web' ? ({ outlineStyle: 'none' } as any) : {}),
  },
  filterContainer: {
    marginBottom: spacing[4],
  },
  filterScroll: {
    paddingHorizontal: spacing[4],
    gap: spacing[2],
  },
  filterPill: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  filterPillActive: {
    backgroundColor: theme.accent,
    borderColor: theme.accent,
  },
  filterPillText: {
    color: theme.text,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.body,
    fontWeight: '600',
  },
  filterPillTextActive: {
    color: theme.onAccent,
    fontWeight: '700',
  },
  gridContainer: {
    paddingHorizontal: spacing[4],
    paddingTop: spacing[2],
  },
  row: {
    justifyContent: 'flex-start',
    gap: spacing[3],
    marginBottom: spacing[6],
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
  },
  emptyText: {
    color: theme.textSecondary,
    fontSize: fontSizes.md,
    fontFamily: fontFamilies.body,
  },
  typeToggle: {
    flexDirection: 'row',
    paddingHorizontal: spacing[4],
    gap: spacing[2],
    marginBottom: spacing[4],
  },
  typePill: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  typePillActive: {
    backgroundColor: theme.accent,
    borderColor: theme.accent,
  },
  typePillText: {
    color: theme.textSecondary,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '600',
  },
  typePillTextActive: {
    color: theme.onAccent,
    fontWeight: '700',
  },
  regionSelectorContainer: {
    marginBottom: spacing[3],
  },
  regionPill: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  regionPillActive: {
    backgroundColor: theme.accent,
    borderColor: theme.accent,
  },
  regionPillText: {
    color: theme.textSecondary,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '600',
  },
  regionPillTextActive: {
    color: theme.onAccent,
    fontWeight: '700',
  },
  subfilterContainer: {
    marginBottom: spacing[5],
  },
  subfilterScroll: {
    paddingHorizontal: spacing[4],
    gap: spacing[2],
  },
  subfilterPill: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1.5],
    borderRadius: radii.full,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  subfilterPillActive: {
    backgroundColor: theme.surfaceHover,
    borderColor: theme.accent,
  },
  subfilterPillText: {
    color: theme.textMuted,
    fontSize: fontSizes.xs,
    fontFamily: fontFamilies.body,
    fontWeight: '600',
  },
  subfilterPillTextActive: {
    color: theme.text,
    fontWeight: '700',
  },
  regionShelf: {
    marginBottom: spacing[5],
  },
  regionShelfTitle: {
    color: theme.text,
    fontSize: fontSizes.lg,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  emptyRegionText: {
    color: theme.textMuted,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.body,
    fontStyle: 'italic',
    paddingHorizontal: spacing[4],
  },
  browseTitle: {
    color: theme.text,
    fontSize: fontSizes.lg,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
    paddingHorizontal: spacing[4],
    marginBottom: spacing[4],
  },
  genreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: spacing[4],
    gap: spacing[3],
  },
  genreCard: {
    height: 76,
    borderRadius: radii.xl,
    justifyContent: 'center',
    paddingHorizontal: spacing[3],
    backgroundColor: theme.elevated,
    borderWidth: 1,
    shadowColor: theme.dark ? '#000000' : theme.text,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  genreCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  genreIconBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  genreCardText: {
    flex: 1,
    color: '#ffffff',
    fontSize: 13,
    fontFamily: fontFamilies.heading,
    fontWeight: '800',
    letterSpacing: 0.2,
    textShadowColor: 'rgba(0,0,0,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  genreHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing[4],
    marginBottom: spacing[3],
    gap: spacing[3],
  },
  backPill: {
    minHeight: 44,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.surface,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    gap: 6,
    borderWidth: 1,
    borderColor: theme.border,
  },
  backPillText: {
    color: theme.text,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '600',
  },
  genreActiveLabel: {
    color: theme.accent,
    fontSize: fontSizes.xl,
    fontFamily: fontFamilies.display,
    fontWeight: '900',
    letterSpacing: -0.3,
    flex: 1,
  },
  filterControlsBar: {
    marginBottom: spacing[4],
  },
  dropdownPill: {
    minHeight: 44,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.surface,
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[2],
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: theme.border,
    gap: 6,
  },
  dropdownPillActive: {
    backgroundColor: theme.accent,
    borderColor: theme.accent,
  },
  dropdownPillText: {
    color: theme.textSecondary,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '600',
  },
  dropdownPillTextActive: {
    color: theme.onAccent,
    fontWeight: '700',
  },
  regionShelfHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing[4],
    marginBottom: spacing[3],
  },
  browseAllBtn: {
    minHeight: 44,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: theme.accentSoft,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1.5],
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: theme.accent,
  },
  browseAllBtnText: {
    color: theme.accent,
    fontSize: fontSizes.xs,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  loadMoreFooter: {
    alignItems: 'center',
    marginVertical: spacing[4],
  },
  loadMoreButton: {
    minHeight: 44,
    justifyContent: 'center',
    backgroundColor: theme.surface,
    paddingHorizontal: spacing[6],
    paddingVertical: spacing[3],
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: theme.border,
  },
  loadMoreButtonText: {
    color: theme.text,
    fontSize: fontSizes.sm,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: theme.elevated,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: spacing[5],
    paddingBottom: Platform.OS === 'ios' ? 40 : spacing[6],
    paddingTop: spacing[3],
    borderTopWidth: 1,
    borderColor: theme.border,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.textMuted,
    alignSelf: 'center',
    marginBottom: spacing[3],
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  modalTitle: {
    color: theme.text,
    fontSize: fontSizes.lg,
    fontFamily: fontFamilies.heading,
    fontWeight: '700',
  },
  modalCloseBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 4,
  },
  modalOption: {
    minHeight: 44,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing[3.5],
    paddingHorizontal: spacing[3],
    borderRadius: radii.md,
    marginBottom: spacing[1],
  },
  modalOptionActive: {
    backgroundColor: theme.accentSoft,
  },
  modalOptionText: {
    color: theme.textSecondary,
    fontSize: fontSizes.md,
    fontFamily: fontFamilies.body,
    fontWeight: '500',
  },
  modalOptionTextActive: {
    color: theme.text,
    fontWeight: '700',
  },
});
