import { Platform, StyleSheet } from "react-native";
import { text, backgrounds, spacing, fontSizes, fontFamilies, accent, radii } from "@orion/shared/tokens";
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: backgrounds.base },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 72,
    paddingRight: spacing[5],
    paddingTop: Platform.OS === 'ios' ? 54 : 32,
    paddingBottom: spacing[3],
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '900',
    fontFamily: fontFamilies.heading,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radii.full,
    borderWidth: 1,
  },
  statusPillConnected: {
    backgroundColor: 'rgba(16, 185, 129, 0.14)',
    borderColor: 'rgba(16, 185, 129, 0.45)',
  },
  statusPillDisconnected: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    borderColor: 'rgba(245, 158, 11, 0.4)',
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  statusText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  pairingContainer: {
    alignItems: 'center',
    paddingHorizontal: spacing[6],
    paddingTop: 20,
    paddingBottom: 40,
  },
  iconContainer: {
    width: 110,
    height: 110,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing[4],
  },
  pulseRing: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 2,
    borderColor: 'rgba(229, 9, 20, 0.25)',
  },
  iconInner: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: 'rgba(229, 9, 20, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(229, 9, 20, 0.35)',
  },
  title: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: spacing[2],
  },
  subtitle: {
    color: text.secondary,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 19,
    marginBottom: spacing[5],
  },
  stepsContainer: {
    width: '100%',
    gap: 10,
    marginBottom: spacing[5],
  },
  stepCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    padding: 12,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  stepNumber: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(229, 9, 20, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepNumberText: {
    color: '#f87171',
    fontSize: 12,
    fontWeight: '900',
  },
  stepText: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  pairingBtnGroup: {
    width: '100%',
    gap: 10,
  },
  primaryConnectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: accent.primary,
    paddingVertical: 14,
    borderRadius: radii.xl,
    shadowColor: accent.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  primaryConnectBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryConnectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 14,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  secondaryConnectBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  remoteLayout: {
    flex: 1,
    paddingHorizontal: spacing[5],
    paddingTop: spacing[2],
  },
  nowPlayingBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    padding: 12,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.35)',
    marginBottom: spacing[4],
  },
  nowPlayingIconGlow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nowPlayingTitle: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  nowPlayingSub: {
    color: text.muted,
    fontSize: 11,
    marginTop: 1,
  },
  disconnectRemoteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
  },
  disconnectRemoteText: {
    color: '#f87171',
    fontSize: 10,
    fontWeight: '800',
  },
  modeTabs: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: radii.xl,
    padding: 4,
    marginBottom: spacing[5],
  },
  modeTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: radii.lg,
  },
  modeTabActive: {
    backgroundColor: accent.primary,
  },
  modeTabText: {
    color: text.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  modeTabTextActive: {
    color: '#fff',
    fontWeight: '900',
  },
  dpadSection: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingBottom: 20,
  },
  navRow: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: spacing[6],
  },
  smallNavBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  dpadOuter: {
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 2,
    borderColor: 'rgba(229, 9, 20, 0.3)',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
  },
  dpadUp: {
    padding: 10,
  },
  dpadMiddleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 10,
  },
  dpadLeft: {
    padding: 10,
  },
  dpadRight: {
    padding: 10,
  },
  dpadDown: {
    padding: 10,
  },
  dpadCenterOk: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: accent.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: accent.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 12,
  },
  okText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '900',
  },
  playbackSection: {
    flex: 1,
    justifyContent: 'center',
    gap: spacing[6],
  },
  seekRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  seekBtn: {
    alignItems: 'center',
    gap: 4,
  },
  seekText: {
    color: text.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  bigPlayBtn: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: accent.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: accent.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 14,
  },
  volumeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    padding: 16,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  volumeTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    overflow: 'hidden',
  },
  volumeFill: {
    height: '100%',
    backgroundColor: accent.primary,
  },
  volumeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
    minWidth: 36,
    textAlign: 'right',
  },
  keyboardSection: {
    flex: 1,
    paddingTop: spacing[4],
    gap: spacing[4],
  },
  keyboardPrompt: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  textInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  textInput: {
    flex: 1,
    color: '#fff',
    fontSize: 14,
  },
  sendTextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: accent.primary,
    paddingVertical: 14,
    borderRadius: radii.xl,
  },
  sendTextBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.88)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing[5],
  },
  glassModalCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#0c0c14',
    borderRadius: radii['2xl'],
    padding: spacing[5],
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
    alignItems: 'center',
  },
  modalMethodTabs: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: radii.lg,
    padding: 3,
    marginBottom: 16,
    width: '100%',
  },
  modalMethodTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 8,
    borderRadius: radii.md,
  },
  modalMethodTabActive: {
    backgroundColor: accent.primary,
  },
  modalMethodTabText: {
    color: text.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  modalMethodTabTextActive: {
    color: '#fff',
    fontWeight: '800',
  },
  modalTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 4,
    textAlign: 'center',
  },
  modalSub: {
    color: text.muted,
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
    marginBottom: spacing[4],
  },
  hiddenPinInput: {
    position: 'absolute',
    opacity: 0,
    width: 1,
    height: 1,
  },
  qrSection: {
    alignItems: 'center',
    width: '100%',
  },
  cameraViewfinder: {
    width: 180,
    height: 180,
    borderRadius: radii.xl,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 2,
    borderColor: accent.primary,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    marginBottom: 16,
  },
  laserScanLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: '#f87171',
    shadowColor: '#f87171',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 6,
  },
  pinSection: {
    alignItems: 'center',
    width: '100%',
  },
  pinInputRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
    paddingVertical: 8,
  },
  pinBox: {
    width: 52,
    height: 62,
    borderRadius: radii.xl,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pinBoxFilled: {
    backgroundColor: 'rgba(229, 9, 20, 0.15)',
    borderColor: 'rgba(229, 9, 20, 0.5)',
  },
  pinBoxFocused: {
    borderColor: accent.primary,
    shadowColor: accent.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
  },
  pinBoxText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '900',
  },
  ipSection: {
    alignItems: 'center',
    width: '100%',
  },
  ipInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    marginBottom: 16,
    width: '100%',
  },
  ipInput: {
    flex: 1,
    color: '#fff',
    fontSize: 15,
  },
  confirmBtn: {
    width: '100%',
    backgroundColor: accent.primary,
    paddingVertical: 13,
    borderRadius: radii.xl,
    alignItems: 'center',
    marginBottom: 8,
  },
  confirmBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  cancelBtnFull: {
    width: '100%',
    paddingVertical: 10,
    alignItems: 'center',
  },
  cancelBtnText: {
    color: text.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  disconnectIconGlow: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
    marginBottom: 12,
  },
  disconnectModalBtnRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
    marginTop: 12,
  },
  cancelBtnModal: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 12,
    borderRadius: radii.xl,
    alignItems: 'center',
  },
  disconnectConfirmBtn: {
    flex: 1,
    backgroundColor: 'rgba(239, 68, 68, 0.9)',
    paddingVertical: 12,
    borderRadius: radii.xl,
    alignItems: 'center',
  },
  disconnectConfirmText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  hudFeatureGrid: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
    marginVertical: 12,
  },
  hudFeatureBtn: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: radii.xl,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  hudFeatureText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  volumePresetRow: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
    marginTop: 8,
  },
  volStepBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingVertical: 10,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  volPresetBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(229, 9, 20, 0.15)',
    paddingVertical: 10,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(229, 9, 20, 0.35)',
  },
  volStepText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  quickLaunchRailContainer: {
    width: '100%',
    marginBottom: 12,
  },
  quickLaunchTitle: {
    color: text.muted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
    paddingLeft: 4,
  },
  quickLaunchRail: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 2,
  },
  quickPageChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.xl,
  },
  quickPageChipText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  focusModeSwitchRow: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
    marginBottom: 12,
  },
  focusModeBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 8,
    borderRadius: radii.lg,
  },
  focusModeBtnActive: {
    backgroundColor: 'rgba(229, 9, 20, 0.18)',
    borderColor: 'rgba(229, 9, 20, 0.5)',
  },
  focusModeText: {
    color: text.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  focusModeTextActive: { color: '#fff' },
  scrubberContainer: {
    width: '100%',
    marginBottom: 16,
  },
  scrubberTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  scrubberTimeText: {
    color: text.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  scrubberTrack: {
    width: '100%',
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    overflow: 'hidden',
    justifyContent: 'center',
  },
  scrubberFill: {
    height: '100%',
    backgroundColor: accent.primary,
    borderRadius: 4,
  },
  touchpadSection: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 12,
  },
  touchpadSurface: {
    width: '100%',
    height: 240,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: radii.xl,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  touchpadPrompt: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  touchpadSubPrompt: {
    color: text.muted,
    fontSize: 12,
  },
});
