import { radii, spacing } from '@orion/shared/tokens';
import type { MobileThemeTokens } from '../../context/ThemeContext';

export const createConnectPairingLayoutStyles = (theme: MobileThemeTokens) => ({
  modalKeyboardAvoider: { flex: 1 },
  modalOverlay: {
    flexGrow: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.88)',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[4],
  },
  modalOverlayPhone: {
    justifyContent: 'flex-end' as const,
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  glassModalCard: {
    width: '100%' as const,
    maxWidth: 400,
    backgroundColor: theme.elevated,
    borderRadius: radii['2xl'],
    padding: spacing[5],
    borderWidth: 1,
    borderColor: theme.danger,
    alignItems: 'center' as const,
  },
  glassModalCardPhone: {
    maxWidth: undefined,
    maxHeight: '88%' as const,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  glassModalCardWide: { maxHeight: '92%' as const, maxWidth: 560 },
  glassModalCardKeyboard: { paddingVertical: spacing[3] },
  verificationSection: {
    width: '100%' as const,
    alignItems: 'center' as const,
    gap: spacing[3],
  },
  verificationEyebrow: {
    color: theme.accent,
    fontSize: 11,
    fontWeight: '900' as const,
    letterSpacing: 2,
    textAlign: 'center' as const,
  },
  verificationPhrase: {
    width: '100%' as const,
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    justifyContent: 'center' as const,
    gap: spacing[2],
    padding: spacing[3],
    borderRadius: radii.xl,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
  },
  verificationWord: {
    minWidth: 112,
    minHeight: 48,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: spacing[2],
    paddingHorizontal: spacing[3],
    borderRadius: radii.lg,
    backgroundColor: theme.accentSoft,
    borderWidth: 1,
    borderColor: theme.accent,
  },
  verificationWordIndex: { color: theme.textMuted, fontSize: 11, fontWeight: '800' as const },
  verificationWordText: { flexShrink: 1, color: theme.text, fontSize: 15, fontWeight: '900' as const },
  verificationExpiry: { color: theme.textMuted, fontSize: 11, lineHeight: 16, textAlign: 'center' as const },
  verificationReject: {
    width: '100%' as const,
    minHeight: 48,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: theme.danger,
  },
  verificationRejectText: { color: theme.danger, fontSize: 13, fontWeight: '900' as const },
  verificationStatus: { color: theme.textSecondary, fontSize: 12, lineHeight: 17, textAlign: 'center' as const },
});
