const { MUSIC_IPC } = require("../../shared/musicConstants.cjs");

module.exports = ({ ipcRenderer }) => ({
  musicGetStatus: () => ipcRenderer.invoke(MUSIC_IPC.STATUS),
  musicListFolders: () => ipcRenderer.invoke(MUSIC_IPC.FOLDERS_LIST),
  musicAddFolder: () => ipcRenderer.invoke(MUSIC_IPC.FOLDERS_ADD),
  musicRemoveFolder: (id) => ipcRenderer.invoke(MUSIC_IPC.FOLDERS_REMOVE, id),
  musicScan: () => ipcRenderer.invoke(MUSIC_IPC.SCAN_START),
  musicCancelScan: () => ipcRenderer.invoke(MUSIC_IPC.SCAN_CANCEL),
  onMusicScanProgress: (callback) => {
    const listener = (_, value) => callback(value);
    ipcRenderer.on(MUSIC_IPC.SCAN_PROGRESS, listener);
    return () => ipcRenderer.removeListener(MUSIC_IPC.SCAN_PROGRESS, listener);
  },
  musicListTracks: (options) => ipcRenderer.invoke(MUSIC_IPC.TRACKS_LIST, options),
  musicResolveTrack: (track, providerId) => ipcRenderer.invoke(MUSIC_IPC.TRACK_GET_STREAM, track, providerId),
  musicListTrackCandidates: (track, providerId) => ipcRenderer.invoke(MUSIC_IPC.TRACK_CANDIDATES, track, providerId),
  musicResolveCandidate: (id) => ipcRenderer.invoke(MUSIC_IPC.TRACK_RESOLVE_CANDIDATE, id),
  musicGetArtwork: (track) => ipcRenderer.invoke(MUSIC_IPC.ARTWORK_GET, track),
  musicGetLyrics: (track) => ipcRenderer.invoke(MUSIC_IPC.LYRICS_GET, track),
  musicSearch: (query) => ipcRenderer.invoke(MUSIC_IPC.SEARCH, query),
  musicGetSearchSuggestions: (query) => ipcRenderer.invoke(MUSIC_IPC.SEARCH_SUGGESTIONS, query),
  musicContinueSearch: (query, continuation) => ipcRenderer.invoke(MUSIC_IPC.SEARCH_CONTINUE, query, continuation),
  musicGetRadio: (item) => ipcRenderer.invoke(MUSIC_IPC.RADIO_GET, item),
  musicGetDashboard: () => ipcRenderer.invoke(MUSIC_IPC.DASHBOARD_GET),
  musicGetDetails: (kind, item) => ipcRenderer.invoke(MUSIC_IPC.DETAILS_GET, kind, item),
  musicListProviders: () => ipcRenderer.invoke(MUSIC_IPC.PROVIDERS_LIST),
  musicSetActiveProvider: (kind, providerId) => ipcRenderer.invoke(MUSIC_IPC.PROVIDER_CONFIGURE, kind, providerId),
  musicConfigureProvider: (providerId, value) => ipcRenderer.invoke(MUSIC_IPC.PROVIDER_SAVE_CONFIG, providerId, value),
  musicListPlugins: () => ipcRenderer.invoke(MUSIC_IPC.PLUGINS_LIST),
  musicInstallPlugin: (id) => ipcRenderer.invoke(MUSIC_IPC.PLUGIN_INSTALL, id),
  musicSetPluginEnabled: (id, enabled) => ipcRenderer.invoke(MUSIC_IPC.PLUGIN_SET_ENABLED, id, enabled),
  musicRemovePlugin: (id) => ipcRenderer.invoke(MUSIC_IPC.PLUGIN_REMOVE, id),
  musicListPlaylists: () => ipcRenderer.invoke(MUSIC_IPC.PLAYLISTS_LIST),
  musicListRemotePlaylists: () => ipcRenderer.invoke(MUSIC_IPC.PLAYLISTS_REMOTE_LIST),
  musicSavePlaylist: (playlist) => ipcRenderer.invoke(MUSIC_IPC.PLAYLISTS_SAVE, playlist),
  musicDeletePlaylist: (id) => ipcRenderer.invoke(MUSIC_IPC.PLAYLISTS_DELETE, id),
  musicImportPlaylist: (providerId, value) => ipcRenderer.invoke(MUSIC_IPC.PLAYLISTS_IMPORT, providerId, value),
  musicImportPlaylistFile: () => ipcRenderer.invoke(MUSIC_IPC.PLAYLISTS_IMPORT_FILE),
  musicExportPlaylistFile: (id, format) => ipcRenderer.invoke(MUSIC_IPC.PLAYLISTS_EXPORT_FILE, id, format),
  musicListPlaylistFolders: () => ipcRenderer.invoke(MUSIC_IPC.PLAYLIST_FOLDERS_LIST),
  musicSavePlaylistFolder: (folder) => ipcRenderer.invoke(MUSIC_IPC.PLAYLIST_FOLDERS_SAVE, folder),
  musicDeletePlaylistFolder: (id) => ipcRenderer.invoke(MUSIC_IPC.PLAYLIST_FOLDERS_DELETE, id),
  musicListFavorites: () => ipcRenderer.invoke(MUSIC_IPC.FAVORITES_LIST),
  musicToggleFavorite: (kind, identity, payload) => ipcRenderer.invoke(MUSIC_IPC.FAVORITES_TOGGLE, kind, identity, payload),
  musicLoadQueue: () => ipcRenderer.invoke(MUSIC_IPC.QUEUE_LOAD),
  musicSaveQueue: (queue) => ipcRenderer.invoke(MUSIC_IPC.QUEUE_SAVE, queue),
  musicAddHistory: (track, positionMs) => ipcRenderer.invoke(MUSIC_IPC.HISTORY_ADD, track, positionMs),
  musicListHistory: (limit) => ipcRenderer.invoke(MUSIC_IPC.HISTORY_LIST, limit),
  musicExportBackup: () => ipcRenderer.invoke(MUSIC_IPC.BACKUP_EXPORT),
  musicImportBackup: (state) => ipcRenderer.invoke(MUSIC_IPC.BACKUP_IMPORT, state),
  musicGetCacheStatus: () => ipcRenderer.invoke(MUSIC_IPC.CACHE_STATUS),
  musicSetCacheLimit: (limitMb) => ipcRenderer.invoke(MUSIC_IPC.CACHE_SET_LIMIT, limitMb),
  musicClearCache: () => ipcRenderer.invoke(MUSIC_IPC.CACHE_CLEAR),
});
