import { Platform, StyleSheet } from 'react-native';
import { radii } from '@orion/shared/tokens';

export const playerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  videoBoxWrapper: {
    width: '100%',
    height: '100%',
    flex: 1,
    alignSelf: 'center',
    backgroundColor: '#000',
  },
  video: { flex: 1 },
  nativeVideoHost: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
    position: 'relative',
    backgroundColor: '#000',
  },
  nativeVideo: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  webVideo: { flex: 1, backgroundColor: '#000' },
  fullWidthHeaderGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingTop: Platform.OS === 'ios' ? 48 : 24,
    paddingBottom: 24,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    zIndex: 999,
  },
  floatingGlassBackBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitleWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  framelessTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  floatingGlassSourceChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 12,
    height: 38,
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
  },
  sourceChipText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  shieldBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    paddingHorizontal: 8,
    height: 38,
    borderRadius: radii.full,
  },
  shieldBadgeVerified: {
    backgroundColor: 'rgba(74, 222, 128, 0.15)',
    borderColor: 'rgba(74, 222, 128, 0.35)',
  },
  shieldBadgeLimited: {
    backgroundColor: 'rgba(251, 191, 36, 0.14)',
    borderColor: 'rgba(251, 191, 36, 0.38)',
  },
  shieldBadgeFailed: {
    backgroundColor: 'rgba(251, 113, 133, 0.14)',
    borderColor: 'rgba(251, 113, 133, 0.38)',
  },
  shieldCounter: {
    minWidth: 12,
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '800',
  },
  shieldCounterVerified: { color: '#4ade80' },
  shieldCounterLimited: { color: '#fbbf24' },
  shieldCounterFailed: { color: '#fb7185' },
  shieldText: {
    color: '#4ade80',
    fontSize: 11,
    fontWeight: '700',
  },
  shieldTextLimited: { color: '#fbbf24' },
  embedHudLayer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 999,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
});
