import { Platform, StyleSheet } from 'react-native';
import { radii } from '@orion/shared/tokens';

export const playerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  videoBoxWrapper: {
    width: '100%',
    height: '100%',
    flex: 1,
    alignSelf: 'center',
    backgroundColor: '#000',
  },
  video: { flex: 1 },
  webVideo: { flex: 1, backgroundColor: '#000' },
  fullWidthHeaderGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingTop: Platform.OS === 'ios' ? 48 : 24,
    paddingBottom: 24,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    zIndex: 999,
  },
  floatingGlassBackBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitleWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  framelessTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  floatingGlassSourceChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 12,
    height: 38,
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
  },
  sourceChipText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  shieldBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(74, 222, 128, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(74, 222, 128, 0.35)',
    paddingHorizontal: 8,
    height: 38,
    borderRadius: radii.full,
  },
  shieldText: {
    color: '#4ade80',
    fontSize: 11,
    fontWeight: '700',
  },
  shieldTextLimited: { color: '#fbbf24' },
  embedRevealHandle: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 38 : 12,
    alignSelf: 'center',
    zIndex: 1000,
    width: 76,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  embedRevealBar: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
});
