const catalog = Object.freeze([
  { id: "orion-core", name: "Orion Music Core", description: "Local library, media controls and secure playback grants.", categories: ["metadata", "streaming", "other"], version: "2.0.0", bundled: true, locked: true, defaultInstalled: true, permissions: ["library:read", "playback:resolve"] },
  { id: "orion-omnisource", name: "OmniSource", description: "Searches every enabled catalog in parallel and preserves alternate provider matches.", categories: ["metadata", "streaming"], version: "1.0.0", bundled: true, defaultInstalled: true, permissions: ["providers:query"] },
  { id: "orion-musicbrainz", name: "MusicBrainz", description: "Artists, releases, recordings, Wikipedia context and Cover Art Archive artwork.", categories: ["metadata"], version: "1.0.0", bundled: true, defaultInstalled: true, permissions: ["network:musicbrainz.org", "network:coverartarchive.org"] },
  { id: "orion-youtube", name: "YouTube", description: "Audio candidate discovery and just-in-time playback through Orion-managed yt-dlp.", categories: ["streaming"], version: "1.0.0", bundled: true, defaultInstalled: true, permissions: ["tools:yt-dlp", "network:youtube.com"] },
  { id: "orion-discogs", name: "Discogs", description: "Artist, album and release metadata from Discogs.", categories: ["metadata"], version: "1.0.0", bundled: true, permissions: ["network:api.discogs.com"] },
  { id: "orion-deezer-dashboard", name: "Deezer Catalog", description: "Searchable track and album metadata, artwork, charts, editorial playlists and new releases.", categories: ["metadata", "dashboard", "playlists"], version: "1.1.0", bundled: true, defaultInstalled: true, permissions: ["network:api.deezer.com"] },
  { id: "orion-lrclib", name: "LRCLib Lyrics", description: "Plain and synchronized lyrics matched by track metadata and duration.", categories: ["lyrics"], version: "1.0.0", bundled: true, defaultInstalled: true, permissions: ["network:lrclib.net"] },
  { id: "orion-listenbrainz", name: "ListenBrainz Dashboard", description: "Global listening charts, popular recordings and release signals.", categories: ["dashboard"], version: "1.0.0", bundled: true, defaultInstalled: true, permissions: ["network:api.listenbrainz.org"] },
  { id: "orion-subsonic", name: "Subsonic / Navidrome", description: "Connect a user-owned music server for catalog, playlists and streaming.", categories: ["metadata", "streaming", "dashboard", "playlists"], version: "1.0.0", bundled: true, defaultInstalled: true, requiresConfiguration: true, permissions: ["network:user-server", "credentials:secure"] },
  { id: "orion-bandcamp", name: "Bandcamp", description: "Bandcamp catalog, streaming and editorial discovery when a reliable permitted interface is available.", categories: ["metadata", "streaming", "dashboard"], version: "0.1.0", bundled: false, status: "planned", permissions: ["network:bandcamp.com"] },
  { id: "orion-soundcloud", name: "SoundCloud", description: "SoundCloud catalog and playable public tracks.", categories: ["metadata", "streaming"], version: "1.0.0", bundled: true, permissions: ["network:soundcloud.com", "tools:yt-dlp"] },
  { id: "orion-spotify", name: "Spotify", description: "Spotify artist, album and track metadata plus playlist import; playback uses another enabled source.", categories: ["metadata", "playlists"], version: "0.1.0", bundled: false, status: "planned", requiresConfiguration: true, permissions: ["network:api.spotify.com", "credentials:secure"] },
  { id: "orion-lastfm", name: "Last.fm", description: "Scrobbling, Now Playing and taste-based discovery.", categories: ["scrobbling", "discovery"], version: "0.1.0", bundled: false, status: "planned", requiresConfiguration: true, permissions: ["network:ws.audioscrobbler.com", "credentials:secure"] },
  { id: "orion-youtube-playlists", name: "YouTube Playlists", description: "Import a public YouTube playlist by URL through Orion-managed yt-dlp.", categories: ["playlists"], version: "1.0.0", bundled: true, permissions: ["tools:yt-dlp", "network:youtube.com"] },
  { id: "orion-khinsider", name: "KHInsider", description: "Optional experimental video-game soundtrack catalog.", categories: ["metadata", "streaming"], version: "0.1.0", bundled: false, status: "experimental", permissions: ["network:downloads.khinsider.com"] },
]);

function getPlugin(id) { return catalog.find((plugin) => plugin.id === id); }
module.exports = { catalog, getPlugin };
