export const allMangaSource = {
  id: "allmanga",
  label: "AllManga",
  releaseStatus: "primary",
  media: { movie: true, tv: true, anime: true },
  idPolicy: { movie: "async", tv: "async" },
  buildMovieUrl: () => "https://allmanga.to",
  buildEpisodeUrl: () => "https://allmanga.to",
  expectedOrigins: ["https://allmanga.to"],
  allowedNavigationOrigins: ["https://allmanga.to"],
  requiredRequestOrigins: ["https://allmanga.to"],
  progressStrategy: "native",
  subtitleStrategy: "provider",
  supportsResume: true,
  supportsExternalSubtitles: false,
  supportsDownloads: true,
  async: true,
  animeOnly: true,
  params: {},
};
