const commonMedia = Object.freeze({ movie: true, tv: true, anime: false });
const tmdbPolicy = Object.freeze({ movie: "tmdb", tv: "tmdb" });

export const primarySources = [
  {
    id: "videasy",
    label: "Videasy",
    releaseStatus: "primary",
    media: commonMedia,
    idPolicy: tmdbPolicy,
    buildMovieUrl: (id) => `https://player.videasy.to/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://player.videasy.to/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://player.videasy.to"],
    allowedNavigationOrigins: ["https://player.videasy.to"],
    requiredRequestOrigins: ["https://player.videasy.to"],
    progressStrategy: "frame-video",
    subtitleStrategy: "request-capture",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: true,
    colorParam: "color",
    params: { overlay: "true" },
  },
  {
    id: "vidsrc",
    label: "VidSrc",
    releaseStatus: "primary",
    media: commonMedia,
    idPolicy: { movie: "imdb-preferred", tv: "imdb-preferred" },
    buildMovieUrl: (id) => `https://vsembed.su/embed/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://vsembed.su/embed/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://vsembed.su"],
    allowedNavigationOrigins: ["https://vsembed.su"],
    requiredRequestOrigins: ["https://vsembed.su"],
    progressStrategy: "frame-video",
    subtitleStrategy: "url-param",
    supportsResume: true,
    supportsExternalSubtitles: true,
    supportsDownloads: true,
    langParam: "ds_lang",
    externalSubtitleParam: "sub_file",
    externalSubtitleLabelParam: "sub_label",
    params: {},
  },
  {
    id: "vidking",
    label: "VidKing",
    releaseStatus: "primary",
    media: commonMedia,
    idPolicy: tmdbPolicy,
    buildMovieUrl: (id) => `https://www.vidking.net/embed/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://www.vidking.net/embed/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://www.vidking.net"],
    allowedNavigationOrigins: ["https://www.vidking.net"],
    requiredRequestOrigins: ["https://www.vidking.net"],
    progressStrategy: "player-event",
    subtitleStrategy: "request-capture",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: true,
    colorParam: "color",
    resumeParam: "progress",
    params: { autoPlay: "true" },
  },
];
