/**
 * Candidate Cinema Sources
 *
 * Ported from desktop's adapters/candidates.js
 */

import type { CinemaSourceDescriptor } from "../contracts";

const media = Object.freeze({ movie: true, tv: true, anime: false });

function cohortMediaId(id: string | number, allowImdb = false): string {
  const value = String(id);
  if (/^[1-9]\d*$/.test(value) || (allowImdb && /^tt\d+$/.test(value))) return value;
  throw new Error(allowImdb ? "A TMDb or IMDb ID is required." : "A positive TMDb ID is required.");
}

function cohortEpisodeNumber(value: number, season = false): number {
  if (Number.isSafeInteger(value) && value >= (season ? 0 : 1)) return value;
  throw new Error("A valid season and episode are required.");
}

export const candidateSources: CinemaSourceDescriptor[] = [
  {
    id: "vidlink",
    label: "VidLink",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "tmdb", tv: "tmdb" },
    buildMovieUrl: (id) => `https://vidlink.pro/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://vidlink.pro/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://vidlink.pro"],
    allowedNavigationOrigins: ["https://vidlink.pro"],
    requiredRequestOrigins: ["https://vidlink.pro"],
    progressStrategy: "player-event",
    resumeStrategy: "verified-seek",
    subtitleStrategy: "url-param",
    supportsResume: true,
    supportsExternalSubtitles: true,
    supportsDownloads: false,
    routingMode: "manual-only",
    availability: "having-trouble",
    availabilityReason: "Playback can still be tried manually; download resolution is disabled until this source is requalified.",
    colorParam: "primaryColor",
    externalSubtitleParam: "sub_file",
    externalSubtitleLabelParam: "sub_label",
    params: { autoplay: "true" },
  },
  {
    id: "vidnest",
    label: "VidNest",
    releaseStatus: "candidate",
    media: { movie: true, tv: true, anime: true },
    idPolicy: { movie: "tmdb", tv: "tmdb" },
    buildMovieUrl: (id) => `https://vidnest.fun/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://vidnest.fun/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://vidnest.fun"],
    allowedNavigationOrigins: ["https://vidnest.fun"],
    requiredRequestOrigins: ["https://vidnest.fun"],
    progressStrategy: "frame-video",
    resumeStrategy: "url-param",
    subtitleStrategy: "request-capture",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: false,
    routingMode: "manual-only",
    availability: "ready",
    availabilityReason: "New source. Try it and choose another if needed.",
    movieResumeParam: "startAt",
    tvResumeParam: "progress",
    params: { prevepisode: "hide", nextepisode: "hide" },
  },
  {
    id: "vidsrc-ir",
    label: "VidSrc.ir",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "imdb-preferred", tv: "imdb-preferred" },
    buildMovieUrl: (id) => `https://vidsrc.ir/embed/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://vidsrc.ir/embed/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://vidsrc.ir"],
    allowedNavigationOrigins: ["https://vidsrc.ir"],
    requiredRequestOrigins: ["https://vidsrc.ir"],
    progressStrategy: "player-event",
    resumeStrategy: "url-param",
    subtitleStrategy: "url-param",
    supportsResume: true,
    supportsExternalSubtitles: true,
    supportsDownloads: false,
    routingMode: "manual-only",
    availability: "having-trouble",
    availabilityReason: "This source is having trouble.",
    resumeParam: "startAt",
    langParam: "ds_lang",
    externalSubtitleParam: "sub_url",
    externalSubtitleLabelParam: "sub_label",
    externalSubtitleLanguageParam: "sub_lang",
    params: { autoplay: "1", autonext: "0" },
  },
  {
    id: "cinesrc",
    label: "CineSrc",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "tmdb", tv: "tmdb" },
    buildMovieUrl: (id) => `https://cinesrc.st/embed/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://cinesrc.st/embed/tv/${id}?s=${season}&e=${episode}`,
    expectedOrigins: ["https://cinesrc.st"],
    allowedNavigationOrigins: ["https://cinesrc.st"],
    requiredRequestOrigins: ["https://cinesrc.st"],
    progressStrategy: "frame-video",
    resumeStrategy: "url-param",
    subtitleStrategy: "provider",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: false,
    routingMode: "manual-only",
    availability: "ready",
    availabilityReason: "New source. Try it and choose another if needed.",
    colorParam: "color",
    resumeParam: "t",
    params: { autoplay: "true", autonext: "false", continueprompt: "false" },
  },
  // Cohort A uses documented parent messages inside Orion's existing wrapper.
  // These capabilities do not assert physical playback or download qualification.
  {
    id: "mapple",
    label: "Mapple",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "tmdb", tv: "tmdb" },
    buildMovieUrl: (id) => `https://mapple.fun/watch/movie/${cohortMediaId(id)}`,
    buildEpisodeUrl: (id, season, episode) => `https://mapple.fun/watch/tv/${cohortMediaId(id)}-${cohortEpisodeNumber(season, true)}-${cohortEpisodeNumber(episode)}`,
    expectedOrigins: ["https://mapple.fun"],
    allowedNavigationOrigins: ["https://orion.local", "https://mapple.fun"],
    requiredRequestOrigins: ["https://mapple.fun"],
    progressStrategy: "player-event",
    playerEventContract: "standard",
    requiresIframeWrapper: true,
    resumeStrategy: "url-param",
    subtitleStrategy: "provider",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: false,
    supportsDiagnosticCapture: true,
    routingMode: "manual-only",
    availability: "ready",
    availabilityReason: "New source. Playback and resume have not been confirmed yet.",
    colorParam: "theme",
    resumeParam: "startAt",
    params: { autoPlay: "true", startAt: "0", title: "false", poster: "false", autoNext: "false", nextButton: "false" },
  },
  {
    id: "stellar",
    label: "Stellar",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "tmdb", tv: "tmdb" },
    buildMovieUrl: (id) => `https://stellar.rip/en/watch/embed/movie/${cohortMediaId(id)}`,
    buildEpisodeUrl: (id, season, episode) => `https://stellar.rip/en/watch/embed/tv/${cohortMediaId(id)}-${cohortEpisodeNumber(season, true)}-${cohortEpisodeNumber(episode)}`,
    expectedOrigins: ["https://stellar.rip"],
    allowedNavigationOrigins: ["https://orion.local", "https://stellar.rip"],
    requiredRequestOrigins: ["https://stellar.rip"],
    progressStrategy: "player-event",
    playerEventContract: "standard",
    playerMessageHandshake: { readyType: "STELLAR_EMBED_READY", initType: "STELLAR_EMBED_INIT" },
    requiresIframeWrapper: true,
    resumeStrategy: "url-param",
    subtitleStrategy: "provider",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: false,
    supportsDiagnosticCapture: true,
    routingMode: "manual-only",
    availability: "ready",
    availabilityReason: "New source. Playback and resume have not been confirmed yet.",
    colorParam: "theme",
    resumeParam: "startAt",
    params: { autoPlay: "true", startAt: "0", title: "false", poster: "false", autoNext: "false", nextButton: "false" },
  },
  {
    id: "chillflix",
    label: "Chillflix",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "tmdb", tv: "tmdb" },
    buildMovieUrl: (id) => `https://www.chillflix.lol/embed/movie/${cohortMediaId(id)}`,
    buildEpisodeUrl: (id, season, episode) => `https://www.chillflix.lol/embed/tv/${cohortMediaId(id)}/${cohortEpisodeNumber(season, true)}/${cohortEpisodeNumber(episode)}`,
    expectedOrigins: ["https://www.chillflix.lol"],
    allowedNavigationOrigins: ["https://orion.local", "https://www.chillflix.lol"],
    requiredRequestOrigins: ["https://www.chillflix.lol"],
    progressStrategy: "player-event",
    playerEventContract: "standard",
    requiresIframeWrapper: true,
    resumeStrategy: "url-param",
    subtitleStrategy: "provider",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: false,
    supportsDiagnosticCapture: true,
    routingMode: "manual-only",
    availability: "ready",
    availabilityReason: "New source. Playback and resume have not been confirmed yet.",
    resumeParam: "startAt",
    params: { autoplay: "true", startAt: "0", title: "false", watchparty: "false", autonext: "false" },
  },
  {
    id: "vidsrc-sh",
    label: "VidSrc.sh",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "imdb-preferred", tv: "imdb-preferred" },
    buildMovieUrl: (id) => `https://vidsrc.sh/embed/movie/${cohortMediaId(id, true)}`,
    buildEpisodeUrl: (id, season, episode) => `https://vidsrc.sh/embed/tv/${cohortMediaId(id, true)}/${cohortEpisodeNumber(season, true)}/${cohortEpisodeNumber(episode)}`,
    expectedOrigins: ["https://vidsrc.sh"],
    allowedNavigationOrigins: ["https://orion.local", "https://vidsrc.sh"],
    requiredRequestOrigins: ["https://vidsrc.sh"],
    progressStrategy: "player-event",
    playerEventContract: "status",
    requiresIframeWrapper: true,
    resumeStrategy: "url-param",
    subtitleStrategy: "url-param",
    supportsResume: true,
    supportsExternalSubtitles: true,
    supportsDownloads: false,
    supportsDiagnosticCapture: true,
    routingMode: "manual-only",
    availability: "ready",
    availabilityReason: "New source. Playback and resume have not been confirmed yet.",
    resumeParam: "startAt",
    langParam: "ds_lang",
    externalSubtitleParam: "sub_url",
    externalSubtitleLabelParam: "sub_label",
    externalSubtitleLanguageParam: "sub_lang",
    params: { autoplay: "1", startAt: "0", autonext: "0" },
  },
  {
    id: "vidapi",
    label: "VidAPI / VAPlayer",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "imdb-preferred", tv: "imdb-preferred" },
    buildMovieUrl: (id) => `https://vaplayer.ru/embed/movie/${cohortMediaId(id, true)}`,
    buildEpisodeUrl: (id, season, episode) => `https://vaplayer.ru/embed/tv/${cohortMediaId(id, true)}/${cohortEpisodeNumber(season, true)}/${cohortEpisodeNumber(episode)}`,
    expectedOrigins: ["https://vaplayer.ru"],
    allowedNavigationOrigins: ["https://orion.local", "https://vaplayer.ru"],
    requiredRequestOrigins: ["https://vaplayer.ru"],
    progressStrategy: "player-event",
    playerEventContract: "status",
    requiresIframeWrapper: true,
    resumeStrategy: "url-param",
    subtitleStrategy: "url-param",
    supportsResume: true,
    supportsExternalSubtitles: true,
    supportsDownloads: false,
    supportsDiagnosticCapture: true,
    routingMode: "manual-only",
    availability: "ready",
    availabilityReason: "New source. Playback depends on this provider allowing Orion's embed origin.",
    resumeParam: "resumeAt",
    langParam: "ds_lang",
    externalSubtitleParam: "sub_url",
    externalSubtitleLabelParam: "sub_label",
    externalSubtitleLanguageParam: "sub_lang",
    params: { autoplay: "1", resumeAt: "0", overlay: "false" },
  },
];
