/**
 * Candidate Cinema Sources
 *
 * Ported from desktop's adapters/candidates.js
 */

import type { CinemaSourceDescriptor } from "../contracts";

const media = Object.freeze({ movie: true, tv: true, anime: false });

export const candidateSources: CinemaSourceDescriptor[] = [
  {
    id: "vidlink",
    label: "VidLink",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "tmdb", tv: "tmdb" },
    buildMovieUrl: (id) => `https://vidlink.pro/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://vidlink.pro/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://vidlink.pro"],
    allowedNavigationOrigins: ["https://vidlink.pro"],
    requiredRequestOrigins: ["https://vidlink.pro"],
    progressStrategy: "player-event",
    resumeStrategy: "verified-seek",
    subtitleStrategy: "url-param",
    supportsResume: true,
    supportsExternalSubtitles: true,
    supportsDownloads: true,
    routingMode: "manual-only",
    availability: "having-trouble",
    availabilityReason: "Playback and manual download can be tried while this source remains under qualification.",
    colorParam: "primaryColor",
    externalSubtitleParam: "sub_file",
    externalSubtitleLabelParam: "sub_label",
    params: { autoplay: "true" },
  },
  {
    id: "vidnest",
    label: "VidNest",
    releaseStatus: "candidate",
    media: { movie: true, tv: true, anime: true },
    idPolicy: { movie: "tmdb", tv: "tmdb" },
    buildMovieUrl: (id) => `https://vidnest.fun/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://vidnest.fun/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://vidnest.fun"],
    allowedNavigationOrigins: ["https://vidnest.fun"],
    requiredRequestOrigins: ["https://vidnest.fun"],
    progressStrategy: "frame-video",
    resumeStrategy: "url-param",
    subtitleStrategy: "request-capture",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: false,
    routingMode: "manual-only",
    availability: "ready",
    availabilityReason: "New source. Try it and choose another if needed.",
    movieResumeParam: "startAt",
    tvResumeParam: "progress",
    params: { prevepisode: "hide", nextepisode: "hide" },
  },
  {
    id: "vidsrc-ir",
    label: "VidSrc.ir",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "imdb-preferred", tv: "imdb-preferred" },
    buildMovieUrl: (id) => `https://vidsrc.ir/embed/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://vidsrc.ir/embed/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://vidsrc.ir"],
    requiresIframeWrapper: true,
    allowedNavigationOrigins: ["https://orion.local", "https://vidsrc.ir"],
    requiredRequestOrigins: ["https://vidsrc.ir"],
    progressStrategy: "player-event",
    resumeStrategy: "url-param",
    subtitleStrategy: "url-param",
    supportsResume: true,
    supportsExternalSubtitles: true,
    supportsDownloads: true,
    routingMode: "manual-only",
    availability: "having-trouble",
    availabilityReason: "This source is having trouble.",
    resumeParam: "startAt",
    langParam: "ds_lang",
    externalSubtitleParam: "sub_url",
    externalSubtitleLabelParam: "sub_label",
    externalSubtitleLanguageParam: "sub_lang",
    params: { autoplay: "1", autonext: "0" },
  },
  {
    id: "cinesrc",
    label: "CineSrc",
    releaseStatus: "candidate",
    media,
    idPolicy: { movie: "tmdb", tv: "tmdb" },
    buildMovieUrl: (id) => `https://cinesrc.st/embed/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://cinesrc.st/embed/tv/${id}?s=${season}&e=${episode}`,
    expectedOrigins: ["https://cinesrc.st"],
    allowedNavigationOrigins: ["https://cinesrc.st"],
    requiredRequestOrigins: ["https://cinesrc.st"],
    progressStrategy: "frame-video",
    resumeStrategy: "url-param",
    subtitleStrategy: "provider",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: true,
    routingMode: "manual-only",
    availability: "ready",
    availabilityReason: "New source. Try it and choose another if needed.",
    colorParam: "color",
    resumeParam: "t",
    params: { autoplay: "true", autonext: "false", continueprompt: "false" },
  },
];
