/**
 * Primary Cinema Sources
 *
 * Ported from desktop's adapters/primary.js
 */

import type { CinemaSourceDescriptor } from "../contracts";

const commonMedia = Object.freeze({ movie: true, tv: true, anime: false });
const tmdbPolicy = Object.freeze({ movie: "tmdb" as const, tv: "tmdb" as const });

export const primarySources: CinemaSourceDescriptor[] = [
  {
    id: "videasy",
    label: "Videasy",
    releaseStatus: "primary",
    media: commonMedia,
    idPolicy: tmdbPolicy,
    buildMovieUrl: (id) => `https://player.videasy.to/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://player.videasy.to/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://player.videasy.to", "https://player.videasy.net"],
    allowedNavigationOrigins: ["https://orion.local", "https://player.videasy.net", "https://player.videasy.to"],
    requiredRequestOrigins: ["https://player.videasy.net", "https://player.videasy.to"],
    progressStrategy: "player-event",
    resumeStrategy: "url-param",
    subtitleStrategy: "request-capture",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: true,
    routingMode: "automatic",
    availability: "ready",
    availabilityReason: "Ready.",
    colorParam: "color",
    resumeParam: "progress",
    requiresIframeWrapper: true,
    params: { overlay: "true" },
  },
  {
    id: "vidsrc",
    label: "VidSrc",
    releaseStatus: "primary",
    media: commonMedia,
    idPolicy: { movie: "imdb-preferred", tv: "imdb-preferred" },
    buildMovieUrl: (id) => `https://vsembed.su/embed/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://vsembed.su/embed/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://vsembed.su"],
    allowedNavigationOrigins: ["https://vsembed.su"],
    requiredRequestOrigins: ["https://vsembed.su"],
    progressStrategy: "frame-video",
    resumeStrategy: "verified-seek",
    subtitleStrategy: "url-param",
    supportsResume: true,
    supportsExternalSubtitles: true,
    supportsDownloads: true,
    routingMode: "manual-only",
    availability: "having-trouble",
    availabilityReason: "This source is not responding reliably.",
    langParam: "ds_lang",
    externalSubtitleParam: "sub_file",
    externalSubtitleLabelParam: "sub_label",
    params: {},
  },
  {
    id: "vidking",
    label: "VidKing",
    releaseStatus: "primary",
    media: commonMedia,
    idPolicy: tmdbPolicy,
    buildMovieUrl: (id) => `https://www.vidking.net/embed/movie/${id}`,
    buildEpisodeUrl: (id, season, episode) => `https://www.vidking.net/embed/tv/${id}/${season}/${episode}`,
    expectedOrigins: ["https://www.vidking.net"],
    allowedNavigationOrigins: ["https://www.vidking.net"],
    requiredRequestOrigins: ["https://www.vidking.net"],
    progressStrategy: "player-event",
    resumeStrategy: "url-param",
    subtitleStrategy: "request-capture",
    supportsResume: true,
    supportsExternalSubtitles: false,
    supportsDownloads: true,
    routingMode: "manual-only",
    availability: "having-trouble",
    availabilityReason: "Playback still needs confirmation.",
    colorParam: "color",
    resumeParam: "progress",
    params: { autoPlay: "true" },
  },
];
